### ISSUE TITLE
Notifications won't show up if DISPLAY=:0.0 is not added

### ISSUE THREAD

**Issue by pedrohqb** [win9z/vaio-s-acpi-script#2]
Just add DISPLAY=:0.0 before su in order to show the notifications. Without that, it didn't work for me. I am using MX Linux 19.

notify() {
    title="$1"
    body="$2"
    
    SENT=""
    for USER in $(users); do
        case $SENT in
            "$USER") ;;
            *" $USER") ;;
            "$USER "*) ;;
            *" $USER "*) ;;
            *) SENT="$SENT $USER"; DISPLAY=:0.0 su $USER -c "notify-send \"$title\" \"$body\"" ;;
        esac
    done
}

**Comment by win9z** [comment]
done
